services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: bioture_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - bioture-network

  nginx:
    image: nginx:alpine
    container_name: bioture_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "23000:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bioture-network
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    container_name: bioture_db
    restart: unless-stopped
    ports:
      - "23004:5432"
    environment:
      POSTGRES_DB: bioture
      POSTGRES_USER: bioture
      POSTGRES_PASSWORD: secret_password
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - bioture-network

networks:
  bioture-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
